[package]
name = "symphonia-bundle-flac"
description = "Pure Rust FLAC demuxer and decoder (a part of project Symphonia)."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "codec", "decoder", "flac"]
# Common package metadata located in workspace Cargo.toml.
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["std"]

std = [
    "log/std",
    "symphonia-core/std",
    "symphonia-common/std",
    "symphonia-metadata/std",
]

[dependencies]
log = { version = "0.4", default-features = false }
symphonia-core = { version = "0.6.0", path = "../symphonia-core", default-features = false }
symphonia-common = { version = "0.6.0", path = "../symphonia-common", default-features = false }

[dependencies.symphonia-metadata]
version = "0.6.0"
path = "../symphonia-metadata"
default-features = false
features = ["flac"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
