#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import sys

NUM_RE = re.compile(r"[-+]?(?:\d*\.\d+|\d+\.\d*|\d+)(?:[eE][-+]?\d+)?")


@dataclass
class ArrayDef:
    size: int | None
    init: str


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*", "", text)
    return text


def strip_directives(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("#"))


def extract_braced(text: str, brace_start: int) -> tuple[str, int]:
    depth = 0
    start = None
    for idx in range(brace_start, len(text)):
        ch = text[idx]
        if ch == "{":
            depth += 1
            if depth == 1:
                start = idx + 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                if start is None:
                    raise ValueError("unbalanced braces")
                return text[start:idx], idx + 1
    raise ValueError("unterminated brace block")


def find_array_defs(text: str, name: str) -> list[ArrayDef]:
    pattern = re.compile(
        rf"\b{re.escape(name)}\s*(?P<dims>(\[[^\]]*\])+)\s*=\s*\{{", re.M
    )
    results: list[ArrayDef] = []
    for match in pattern.finditer(text):
        dims = match.group("dims")
        first_dim = dims.split("]")[0].lstrip("[").strip()
        size_raw = first_dim
        size = int(size_raw) if size_raw.isdigit() else None
        brace_start = text.find("{", match.end() - 1)
        try:
            init, _ = extract_braced(text, brace_start)
        except ValueError:
            continue
        results.append(ArrayDef(size=size, init=init))
    return results


def parse_numbers(init: str) -> list[str]:
    cleaned = strip_directives(strip_comments(init))
    return NUM_RE.findall(cleaned)


def parse_ints(init: str) -> list[int]:
    return [int(x) for x in parse_numbers(init)]


def format_rust_array(items: list[str], indent: str = "    ", items_per_line: int = 8) -> str:
    lines = []
    for idx in range(0, len(items), items_per_line):
        chunk = ", ".join(items[idx : idx + items_per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def write_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def ensure_length(actual: int, expected: int, name: str) -> None:
    if actual != expected:
        raise ValueError(f"{name} length {actual} != {expected}")


def gen_cwrs(out_dir: Path, celt_dir: Path) -> None:
    text = (celt_dir / "cwrs.c").read_text(encoding="utf-8")
    data_defs = find_array_defs(text, "CELT_PVQ_U_DATA")
    if not data_defs:
        raise ValueError("CELT_PVQ_U_DATA not found")
    data_def = max(data_defs, key=lambda d: d.size or 0)
    data = [str(x) for x in parse_ints(data_def.init)]
    ensure_length(len(data), 1488, "CELT_PVQ_U_DATA")

    row_defs = find_array_defs(text, "CELT_PVQ_U_ROW")
    if not row_defs:
        raise ValueError("CELT_PVQ_U_ROW not found")
    row_def = max(row_defs, key=lambda d: d.size or 0)
    offsets = [str(x) for x in parse_ints(row_def.init)]
    ensure_length(len(offsets), 15, "CELT_PVQ_U_ROW offsets")

    lines = [
        "// Auto-generated by scripts/gen_celt_tables.py. Do not edit.",
        "pub const CELT_PVQ_U_DATA: [u32; 1488] = [",
        format_rust_array(data, items_per_line=8),
        "];",
        "",
        "pub const CELT_PVQ_U_ROW_OFFSETS: [usize; 15] = [",
        format_rust_array(offsets, items_per_line=8),
        "];",
        "",
    ]
    write_file(out_dir / "cwrs_tables.rs", "\n".join(lines))


def select_int_def(defs: list[ArrayDef], name: str) -> ArrayDef:
    for definition in defs:
        tokens = parse_numbers(definition.init)
        if all("." not in tok and "e" not in tok and "E" not in tok for tok in tokens):
            return definition
    raise ValueError(f"no integer definition found for {name}")


def find_scalar_defs(text: str, name: str) -> list[str]:
    pattern = re.compile(rf"\b{re.escape(name)}\s*=\s*([^;]+);")
    return [expr.strip() for expr in pattern.findall(text)]


def select_int_scalar(text: str, name: str) -> int:
    for expr in find_scalar_defs(text, name):
        if re.fullmatch(r"[+-]?\d+", expr):
            return int(expr)
    raise ValueError(f"no integer scalar definition found for {name}")


def gen_quant_bands(out_dir: Path, celt_dir: Path) -> None:
    text = (celt_dir / "quant_bands.c").read_text(encoding="utf-8")

    e_means_def = select_int_def(find_array_defs(text, "eMeans"), "eMeans")
    e_means = [int(x) for x in parse_numbers(e_means_def.init)]
    ensure_length(len(e_means), 25, "eMeans")
    e_means_vals = [f"{val / 16.0:.6f}" for val in e_means]

    pred_def = select_int_def(find_array_defs(text, "pred_coef"), "pred_coef")
    pred_vals = [int(x) for x in parse_numbers(pred_def.init)]
    ensure_length(len(pred_vals), 4, "pred_coef")
    pred_vals = [f"{val / 32768.0:.8f}" for val in pred_vals]

    beta_def = select_int_def(find_array_defs(text, "beta_coef"), "beta_coef")
    beta_vals = [int(x) for x in parse_numbers(beta_def.init)]
    ensure_length(len(beta_vals), 4, "beta_coef")
    beta_vals = [f"{val / 32768.0:.8f}" for val in beta_vals]

    beta_intra_val = select_int_scalar(text, "beta_intra")
    beta_intra = f"{beta_intra_val / 32768.0:.8f}"

    prob_defs = find_array_defs(text, "e_prob_model")
    if not prob_defs:
        raise ValueError("e_prob_model not found")
    prob_vals = parse_ints(prob_defs[0].init)
    ensure_length(len(prob_vals), 4 * 2 * 42, "e_prob_model")

    icdf_defs = find_array_defs(text, "small_energy_icdf")
    if not icdf_defs:
        raise ValueError("small_energy_icdf not found")
    icdf_vals = [str(x) for x in parse_ints(icdf_defs[0].init)]
    ensure_length(len(icdf_vals), 3, "small_energy_icdf")

    lines = [
        "// Auto-generated by scripts/gen_celt_tables.py. Do not edit.",
        "pub const E_MEANS: [CeltGlog; 25] = [",
        format_rust_array(e_means_vals, items_per_line=9),
        "];",
        "",
        "const PRED_COEF: [f32; 4] = [",
        format_rust_array(pred_vals, items_per_line=4),
        "];",
        "",
        "const BETA_COEF: [f32; 4] = [",
        format_rust_array(beta_vals, items_per_line=4),
        "];",
        "",
        f"const BETA_INTRA: f32 = {beta_intra};",
        "",
        "const E_PROB_MODEL: [[[u8; 42]; 2]; 4] = [",
    ]

    idx = 0
    for _ in range(4):
        lines.append("    [")
        for _ in range(2):
            chunk = [str(x) for x in prob_vals[idx : idx + 42]]
            idx += 42
            lines.append("        [")
            lines.append(format_rust_array(chunk, indent="            ", items_per_line=14))
            lines.append("        ],")
        lines.append("    ],")
    lines.append("];\n")

    lines.extend(
        [
            "const SMALL_ENERGY_ICDF: [u8; 3] = [",
            format_rust_array(icdf_vals, items_per_line=3),
            "];",
            "",
        ]
    )

    write_file(out_dir / "quant_bands_tables.rs", "\n".join(lines))


def gen_static_modes(out_dir: Path, celt_dir: Path) -> None:
    modes_text = (celt_dir / "modes.c").read_text(encoding="utf-8")
    static_text = (celt_dir / "static_modes_float.h").read_text(encoding="utf-8")

    eband_def = find_array_defs(modes_text, "eband5ms")[0]
    eband_vals = [str(x) for x in parse_ints(eband_def.init)]
    ensure_length(len(eband_vals), 22, "eband5ms")

    band_def = find_array_defs(modes_text, "band_allocation")[0]
    band_vals = [str(x) for x in parse_ints(band_def.init)]
    ensure_length(len(band_vals), 231, "band_allocation")

    window_def = find_array_defs(static_text, "window120")[0]
    window_vals = parse_numbers(window_def.init)
    ensure_length(len(window_vals), 120, "window120")

    logn_def = find_array_defs(static_text, "logN400")[0]
    logn_vals = [str(x) for x in parse_ints(logn_def.init)]
    ensure_length(len(logn_vals), 21, "logN400")

    cache_index_def = find_array_defs(static_text, "cache_index50")[0]
    cache_index_vals = [str(x) for x in parse_ints(cache_index_def.init)]
    ensure_length(len(cache_index_vals), 105, "cache_index50")

    cache_bits_def = find_array_defs(static_text, "cache_bits50")[0]
    cache_bits_vals = [str(x) for x in parse_ints(cache_bits_def.init)]
    ensure_length(len(cache_bits_vals), 392, "cache_bits50")

    cache_caps_def = find_array_defs(static_text, "cache_caps50")[0]
    cache_caps_vals = [str(x) for x in parse_ints(cache_caps_def.init)]
    ensure_length(len(cache_caps_vals), 168, "cache_caps50")

    twiddle_def = find_array_defs(static_text, "fft_twiddles48000_960")[0]
    twiddle_nums = parse_numbers(twiddle_def.init)
    ensure_length(len(twiddle_nums), 480 * 2, "fft_twiddles48000_960")
    twiddle_pairs = [
        f"KissTwiddleCpx {{ r: {twiddle_nums[i]}, i: {twiddle_nums[i + 1]} }}"
        for i in range(0, len(twiddle_nums), 2)
    ]

    bitrev_480_def = find_array_defs(static_text, "fft_bitrev480")[0]
    bitrev_480_vals = [str(x) for x in parse_ints(bitrev_480_def.init)]
    ensure_length(len(bitrev_480_vals), 480, "fft_bitrev480")

    bitrev_240_def = find_array_defs(static_text, "fft_bitrev240")[0]
    bitrev_240_vals = [str(x) for x in parse_ints(bitrev_240_def.init)]
    ensure_length(len(bitrev_240_vals), 240, "fft_bitrev240")

    bitrev_120_def = find_array_defs(static_text, "fft_bitrev120")[0]
    bitrev_120_vals = [str(x) for x in parse_ints(bitrev_120_def.init)]
    ensure_length(len(bitrev_120_vals), 120, "fft_bitrev120")

    bitrev_60_def = find_array_defs(static_text, "fft_bitrev60")[0]
    bitrev_60_vals = [str(x) for x in parse_ints(bitrev_60_def.init)]
    ensure_length(len(bitrev_60_vals), 60, "fft_bitrev60")

    mdct_def = find_array_defs(static_text, "mdct_twiddles960")[0]
    mdct_vals = parse_numbers(mdct_def.init)
    ensure_length(len(mdct_vals), 1800, "mdct_twiddles960")

    lines = [
        "// Auto-generated by scripts/gen_celt_tables.py. Do not edit.",
        "pub static EBAND_5MS: [i16; 22] = [",
        format_rust_array(eband_vals, items_per_line=11),
        "];",
        "",
        "pub static BAND_ALLOCATION: [u8; 231] = [",
        format_rust_array(band_vals, items_per_line=16),
        "];",
        "",
        "pub static WINDOW_120: [CeltCoef; 120] = [",
        format_rust_array(window_vals, items_per_line=8),
        "];",
        "",
        "pub static LOG_N_400: [i16; 21] = [",
        format_rust_array(logn_vals, items_per_line=11),
        "];",
        "",
        "pub static CACHE_INDEX_50: [i16; 105] = [",
        format_rust_array(cache_index_vals, items_per_line=12),
        "];",
        "",
        "pub static CACHE_BITS_50: [u8; 392] = [",
        format_rust_array(cache_bits_vals, items_per_line=16),
        "];",
        "",
        "pub static CACHE_CAPS_50: [u8; 168] = [",
        format_rust_array(cache_caps_vals, items_per_line=12),
        "];",
        "",
        "pub static FFT_TWIDDLES_48000_960: [KissTwiddleCpx; 480] = [",
        format_rust_array(twiddle_pairs, items_per_line=2),
        "];",
        "",
        "pub static FFT_BITREV_480: [i16; 480] = [",
        format_rust_array(bitrev_480_vals, items_per_line=12),
        "];",
        "",
        "pub static FFT_BITREV_240: [i16; 240] = [",
        format_rust_array(bitrev_240_vals, items_per_line=12),
        "];",
        "",
        "pub static FFT_BITREV_120: [i16; 120] = [",
        format_rust_array(bitrev_120_vals, items_per_line=12),
        "];",
        "",
        "pub static FFT_BITREV_60: [i16; 60] = [",
        format_rust_array(bitrev_60_vals, items_per_line=12),
        "];",
        "",
        "pub static MDCT_TWIDDLES_960: [CeltCoef; 1800] = [",
        format_rust_array(mdct_vals, items_per_line=8),
        "];",
        "",
    ]

    write_file(out_dir / "static_modes_tables.rs", "\n".join(lines))


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    celt_dir = repo_root / "opus-1.6.1" / "celt"
    out_dir = repo_root / "src" / "celt" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)

    gen_cwrs(out_dir, celt_dir)
    gen_quant_bands(out_dir, celt_dir)
    gen_static_modes(out_dir, celt_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
