[package]
name = "symphonia-codec-opus"
description = "Pure Opus decoder (a part of project Symphonia)."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "codec", "decoder", "opus"]
# Common package metadata located in workspace Cargo.toml.
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
log = { version = "0.4", default-features = false }
libm = { version = "0.2", default-features = false }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
symphonia-core = { version = "0.6.0", path = "../symphonia-core", default-features = false }

[features]
default = ["std"]
std = ["symphonia-core/std"]

[dev-dependencies]
symphonia-test = { version = "0.6.0", path = "../symphonia-test" }
