[package]
name = "symphonia-core"
description = "Project Symphonia shared structs, traits, and features."
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "codec", "decoder", "multimedia", "media"]
# Common package metadata located in workspace Cargo.toml.
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["std"]

std = [
    "ciborium-io/std",
    "log/std",
    "num-complex/std",
]

# SIMD support.
opt-simd-sse = ["rustfft/sse", "std"]
opt-simd-avx = ["rustfft/avx", "std"]
opt-simd-neon = ["rustfft/neon", "std"]

# Enable all SIMD support.
opt-simd = [
    "opt-simd-sse",
    "opt-simd-avx",
    "opt-simd-neon",
]

# Experimental features.
exp-subtitle-codecs = []
exp-video-codecs = []

[dependencies]
bitflags = "2.4.2"
bytemuck = "1.7"
hashbrown = { version = "0.16", default-features = false, features = ["alloc", "default-hasher"] }
lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
num-complex = { version = "0.4", default-features = false, features = ["libm"] }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
smallvec = "1.13.1"
ciborium-io = { version = "0.2", default-features = false, features = ["alloc"] }

[dependencies.rustfft]
version = "6.1.0"
optional = true
default-features = false

[dev-dependencies.rand]
version = "0.9.2"
features = ["small_rng"]
default-features = false
